"use client"
import CartContextProvider from '@/components/CartContext'
import { Roboto } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import { createGlobalStyle } from 'styled-components'
import 'react-toastify/dist/ReactToastify.css';

const inter = Roboto({ subsets: ['latin'], weight: "400" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const GlobalStyles = createGlobalStyle`
  body{
      padding: 0;
      margin: 0;
      background-color: #eee
    }
`;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalStyles />

      <body className={inter.className}>
        <CartContextProvider>
          {children}
        </CartContextProvider>

        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  )
}
