"use client"
import CartContextProvider from '@/components/CartContext'
import { Roboto } from 'next/font/google'
import { createGlobalStyle } from 'styled-components'

const inter = Roboto({ subsets: ['latin'], weight: "400" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const GlobalStyles = createGlobalStyle`
  body{
      padding: 0;
      margin: 0;
      background-color: #eee
    }
`;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GlobalStyles />

      <body className={inter.className}>
        <CartContextProvider>
          {children}
        </CartContextProvider>
      </body>
    </html>
  )
}
